#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Nov 11 18:39:02 IST 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim core_tb_behav -key {Behavioral:sim_1:Functional:core_tb} -tclbatch core_tb.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -view /home/agamubuntu/Github/processor/riscv/core_tb_behav.wcfg -log simulate.log"
xsim core_tb_behav -key {Behavioral:sim_1:Functional:core_tb} -tclbatch core_tb.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -view /home/agamubuntu/Github/processor/riscv/core_tb_behav.wcfg -log simulate.log

