# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/agamubuntu/Github/processor/core/pynq/constraints.xdc

# IP: ip/data_mem/data_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_mem || ORIG_REF_NAME==data_mem} -quiet] -quiet

# IP: ip/div_unsigned_gen/div_unsigned_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_unsigned_gen || ORIG_REF_NAME==div_unsigned_gen} -quiet] -quiet

# IP: ip/div_signed_gen/div_signed_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_signed_gen || ORIG_REF_NAME==div_signed_gen} -quiet] -quiet

# IP: ip/instr_mem_gen/instr_mem_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==instr_mem_gen || ORIG_REF_NAME==instr_mem_gen} -quiet] -quiet

# XDC: /home/agamubuntu/Github/processor/riscv/riscv.gen/sources_1/ip/data_mem/data_mem_ooc.xdc

# XDC: /home/agamubuntu/Github/processor/riscv/riscv.gen/sources_1/ip/instr_mem_gen/instr_mem_gen_ooc.xdc
