# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/agamubuntu/Github/processor/riscv/riscv.srcs/sources_1/bd/design_1/ip/design_1_core_0_0/design_1_core_0_0.xci
# IP: The module: 'design_1_core_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/agamubuntu/Github/processor/riscv/riscv.srcs/sources_1/ip/data_mem/data_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_mem || ORIG_REF_NAME==data_mem} -quiet] -quiet

# IP: /home/agamubuntu/Github/processor/riscv/riscv.srcs/sources_1/ip/div_unsigned_gen/div_unsigned_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_unsigned_gen || ORIG_REF_NAME==div_unsigned_gen} -quiet] -quiet

# IP: /home/agamubuntu/Github/processor/riscv/riscv.srcs/sources_1/ip/div_signed_gen/div_signed_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_signed_gen || ORIG_REF_NAME==div_signed_gen} -quiet] -quiet

# IP: /home/agamubuntu/Github/processor/riscv/riscv.srcs/sources_1/ip/instr_mem_gen/instr_mem_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==instr_mem_gen || ORIG_REF_NAME==instr_mem_gen} -quiet] -quiet

# XDC: /home/agamubuntu/Github/processor/riscv/riscv.gen/sources_1/ip/data_mem/data_mem_ooc.xdc

# XDC: /home/agamubuntu/Github/processor/riscv/riscv.gen/sources_1/ip/instr_mem_gen/instr_mem_gen_ooc.xdc

# XDC: /home/agamubuntu/Github/processor/riscv/riscv.gen/sources_1/bd/design_1/ip/design_1_core_0_0/design_1_core_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_core_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/agamubuntu/Github/processor/riscv/riscv.srcs/sources_1/bd/design_1/ip/design_1_core_0_0/design_1_core_0_0.xci
# IP: The module: 'design_1_core_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/agamubuntu/Github/processor/riscv/riscv.srcs/sources_1/ip/data_mem/data_mem.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_mem || ORIG_REF_NAME==data_mem} -quiet] -quiet

# IP: /home/agamubuntu/Github/processor/riscv/riscv.srcs/sources_1/ip/div_unsigned_gen/div_unsigned_gen.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_unsigned_gen || ORIG_REF_NAME==div_unsigned_gen} -quiet] -quiet

# IP: /home/agamubuntu/Github/processor/riscv/riscv.srcs/sources_1/ip/div_signed_gen/div_signed_gen.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_signed_gen || ORIG_REF_NAME==div_signed_gen} -quiet] -quiet

# IP: /home/agamubuntu/Github/processor/riscv/riscv.srcs/sources_1/ip/instr_mem_gen/instr_mem_gen.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==instr_mem_gen || ORIG_REF_NAME==instr_mem_gen} -quiet] -quiet

# XDC: /home/agamubuntu/Github/processor/riscv/riscv.gen/sources_1/ip/data_mem/data_mem_ooc.xdc

# XDC: /home/agamubuntu/Github/processor/riscv/riscv.gen/sources_1/ip/instr_mem_gen/instr_mem_gen_ooc.xdc

# XDC: /home/agamubuntu/Github/processor/riscv/riscv.gen/sources_1/bd/design_1/ip/design_1_core_0_0/design_1_core_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_core_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
